#+STARTUP: beamer
#+LaTeX_CLASS: beamer
#+LaTeX_CLASS_OPTIONS: [9pt]

#+latex_header: \mode<beamer>{\usetheme{Warsaw}}
#+latex_header: \mode<beamer>{\setbeamertemplate{blocks}[rounded][shadow=false]}
#+latex_header: \mode<beamer>{\addtobeamertemplate{block begin}{\pgfsetfillopacity{0.8}}{\pgfsetfillopacity{1}}}
#+latex_header: \mode<beamer>{\setbeamercolor{structure}{fg=orange}}
#+latex_header: \mode<beamer>{\setbeamercovered{transparent}}
#+latex_header: \AtBeginSection[]{\begin{frame}<beamer>\frametitle{Topic}\tableofcontents[currentsection]\end{frame}}

#+latex_header: \usepackage{subcaption}
#+latex_header: \usepackage{multimedia}
#+latex_header: \usepackage{tikz}
#+latex_header: \usepackage{subfigure,subfigmat}
#+latex_header: \usepackage{threeparttable}
#+latex_header: \usetikzlibrary{shapes,arrows,shadows}
#+latex_header: \usepackage{bm, amssymb, amsmath, array, pdfpages}

#+begin_latex
% Define my settings

\graphicspath{{Figures/}}
% Add Princeton shield logo
\addtobeamertemplate{frametitle}{}{%
\begin{tikzpicture}[remember picture,overlay]
\node[anchor=north east,yshift=2pt] at (current page.north east) {\includegraphics[height=0.7cm]{Shield}};
\end{tikzpicture}}
%
#+end_latex

#+latex_header: \newcommand{\bv}[1]{\mathbf{#1}}
#+latex_header: \newcommand{\diff}[2]{\frac{\partial #1}{\partial #2}}
#+latex_header: \newcommand{\beq}[0]{\begin{equation}}
#+latex_header: \newcommand{\eeq}[0]{\end{equation}}
#+latex_header: \newcommand{\beqa}[0]{\begin{eqnarray}}
#+latex_header: \newcommand{\eeqa}[0]{\end{eqnarray}}
#+latex_header: \newcommand{\beqq}[0]{\begin{equation*}}
#+latex_header: \newcommand{\eeqq}[0]{\end{equation*}}
#+latex_header: \newcommand{\bs}[1]{\boldsymbol{#1}}
#+latex_header: \newcommand{\ip}[2]{\langle #1, #2\rangle}
#+BEAMER_FRAME_LEVEL: 2

#+DATE: FAA JUP Summer 2015 Quarterly Meeting \\ Athens, OH \\ August 2015
#+TITLE: Low-Dimensional Modeling and Uncertainty Quantification for Airfoil Icing
#+AUTHOR: Anthony DeGennaro \newline Clarence W. Rowley III \newline Luigi Martinelli \newline Princeton University
\institute{Princeton University}


* Motivation/Background

** Introduction
*Motivation*
- Wing icing is a serious issue for pilots
  - Massive flow separation, lower lift + higher drag
  - Unpredictable stall
- Wing ice shapes exhibit wide variation, sensitivity to physical
  parameters
  - Complex physics (coupled airflow-thermodynamics)
  - Uncertainty in physical parameters
*Research Goals*
- How can observed variations in ice shape be modeled
  efficiently with a low number of parameters?
- How does uncertainty in the ice shape create uncertainty in
  aerodynamic performance?

** Experimental/Computational Variation in Ice Shape

\vspace*{-0.5cm}\begin{figure}
  \begin{subfigmatrix}{2}
      \subfigure[Habashi, 2006]{\includegraphics[width=0.4\textwidth]{Habashi2006ShapeVariation}}
      \subfigure[Wright, 2004]{\includegraphics[width=0.4\textwidth]{Wright2004ShapeVariation}}
  \end{subfigmatrix}
\end{figure}

- Wide variation in experimental/computational ice shapes[fn:Habashi][fn:Wright]
- Suggests sensitivity to perturbations in underlying physical
  processes
- /UQ approach:/ parameterize the shape variation and study its
  effects on aerodynamics

[fn:Habashi] Beaugendre H., Morency M., and Habashi W.G. /Development
of a Second Generation in-Flight Icing Simulation Code/. Journal of
Fluids Engineering, ASME, 2006.
[fn:Wright] Wright W. and Potapczuk, M.G. /Semi-Empirical Modeling of
SLD Physics/, AIAA 2004-412. 42$^{nd}$ AIAA Aerospace Sciences
Meeting, Reno, NV, 2004.

** Previous Work: Heuristic UQ

#+begin_latex
\begin{columns}[c]
  \column{0.33\textwidth}
    \centering
    \includegraphics[width=0.95\textwidth]{RidgeRVariation} \\
    \includegraphics[width=0.95\textwidth]{RidgeSVariation} \\
    {\bf Ridge}
  \column{0.33\textwidth}
    \centering
    \includegraphics[width=0.95\textwidth]{HornHVariation} \\
    \includegraphics[width=0.95\textwidth]{HornSVariation} \\
    {\bf Horn}
  \column{0.33\textwidth}
    \centering    
    \includegraphics[width=0.9\textwidth]{MC_surrogate_LargeUnc_CL} \\
    \includegraphics[width=0.9\textwidth]{MCgpcPDFLargeUnc_CL} \\
    {\bf Statistics}
\end{columns}
#+end_latex

- Previous study examined parameterized ridge and horn ice
  shapes[fn:DeGennaro]
- Approach was heuristic, not directly based on observed shape
  variations
- Parameter space was low dimensional; no low-dimensional modeling

[fn:DeGennaro] DeGennaro A., Rowley C.W., and Martinelli,
L. /Uncertainty Quantification for Airfoil Icing using Polynomial
Chaos Expansions/. Journal of Aircraft, 2015.

** Previous Work: Data-Driven UQ
\begin{figure}
  \centering
  \includegraphics[width=0.7\textwidth]{Dataset}
\end{figure}

- *Select a database of ice shapes*
  - 54 ice shapes, exposed to a wide range of various icing conditions
    consistent with FAA certification guidelines[fn:Addy]

[fn:Addy] Addy, H.E. /Ice Accretions and Icing Effects for Modern
Airfoils/. NASA TR 2000-210031.
** Previous Work: Data-Driven UQ
#+begin_latex
\begin{columns}[c]
  \column{0.45\textwidth}
    \centering
    \hspace{-2.17em}
    \includegraphics[width=0.9\textwidth]{MEAN.png} \\
    {\bf Mean} \\
    \includegraphics[width=1\textwidth]{MODE2.png} \\
    {\bf Mode 2} \\
    \includegraphics[width=1\textwidth]{MODE4.png} \\
    {\bf Mode 4}
  \column{0.45\textwidth}
    \centering
    \includegraphics[width=1\textwidth]{MODE1.png} \\
    {\bf Mode 1} \\
    \includegraphics[width=1\textwidth]{MODE3.png} \\
    {\bf Mode 3} \\
    \includegraphics[width=1\textwidth]{MODE5.png} \\
    {\bf Mode 5}
\end{columns}
#+end_latex

- *Model using POD*
\begin{equation*}
I(\bv{x}) = \overbar{I(\bv{x})} + \sum_{i=1}^M c_i \Phi_i(\bv{x})
\end{equation*}

** Previous Work: Data-Driven UQ
\begin{figure}
  \centering
  \includegraphics[width=0.7\textwidth]{GoodBadHornExamps}
\end{figure}

- *Analyze statistical trends* [fn:DeGennaroAIAA2015]
  - Most/least ``harmful" model shapes are red/green above
  - Quantify aerodynamic performance metric PDFs given input PDF on
    POD parameter space
  - Correlate different input parameters with aerodynamic performance

[fn:DeGennaroAIAA2015] DeGennaro A., Rowley C.W., and Martinelli
L. /Data-Driven Low-Dimensional Modeling and Uncertainty
Quantification for Airfoil Icing/. AIAA 2015-3383.


* Computational-Based UQ

** Motivation
- *Investigate uncertainty in the physical process of icing*
  - Droplet diameter distribution
    - Affects collection efficiency
  - Droplet temperature distribution
    - Affects convective heat transfer
    - Affects surface tension --> surface roughness
  - Surface roughness
    - Can affect local convective heat transfer
    - Can influence local rate of ice accretion

#+end_latex
** Droplet Diameter Distribution
#+begin_latex
\begin{columns}[c]
  \column{0.5\textwidth}
    \centering
    \includegraphics[width=1\textwidth]{FAADropletDist1} \\
    {\bf Freezing Drizzle MVD PDF}
  \column{0.5\textwidth}
    \centering
    \includegraphics[width=1\textwidth]{FAADropletDist2} \\
    {\bf Freezing Rain MVD PDF}
\end{columns}
#+end_latex

- Several MVD distributions exist for different flight conditions [fn:FAARegs]
- Each gives a different collection efficiency
- How sensitive are collection efficiency and ice shape to perturbations in MVD distribution?

[fn:FAARegs] Airplane and Engine Certification Requirements in
Supercooled Large Drop, Mixed Phase, and Ice Crystal Icing Conditions;
Final Rule. Federal Register, Vol. 79, No. 213.

** Surface Tension vs. Temperature
\begin{figure}
  \centering
  \includegraphics[width=0.33\textwidth]{SurfaceTensionVsTemp.jpeg} \\
  {\bf Surface Tension vs. Temperature}
\end{figure}

- Surface tension of SLDs varies with temperature [fn:SurfTens]
- Varying surface tension can affect collection efficiency
- Higher surface tension may give rise to ``beading" on surface
  (vs. deposition into film), which could affect surface roughness

[fn:SurfTens] Hruby, J. et. al. Surface Tension of Supercooled Water:
No Inflection Point down -25 Degrees
Celsius. J. Phys. Chem. Lett. 2014, 5, 425-28.

** Roughness Variations
\begin{figure}
  \centering
  \includegraphics[width=1\textwidth]{IcingRoughness.png} \\
  {\bf Roughness Growth}
\end{figure}

- *Surface roughness varies with parameters* [fn:Shin]
  - Roughness height increases with temperature and LWC
  - Beginning of roughness varies with temperature, speed, LWC
- *Surface roughness affects shape/aerodynamics* [fn:Shin]
  - Roughness elements probably protrude out of boundary layer and cause transition
  - Irregularity of shape should be calculated by ice accretion code, not treated as part of roughness model

[fn:Shin] Shin, J. Characteristics of Surface Roughness Associated
with Leading-Edge Ice Accretion. Journal of Aircraft, Vol. 33, No.2,
April 1996.

** Airfoil Icing Code Flowchart 

#+begin_latex
\fontsize{7}\selectfont
% Define the layers to draw the diagram
\pgfdeclarelayer{background}
\pgfdeclarelayer{foreground}
\pgfsetlayers{background,main,foreground}

% Define block styles used later

\tikzstyle{sensor}=[draw, fill=blue!20, text width=5em, 
    text centered, minimum height=2.5em,drop shadow]
\tikzstyle{ann} = [above, text width=5em, text centered]
\tikzstyle{wa} = [sensor, text width=7.5em, fill=blue!20, 
    minimum height=3em, rounded corners, drop shadow]

% Define distances for bordering
\def\blockdist{2.3}
\def\edgedist{2.5}

\begin{tikzpicture}
    \node (CleanAirfoil) [wa]  {Clean Airfoil Geometry};
    \path (CleanAirfoil)+(4,2.5) node (FlowSolver) [wa] {Mesh/Flow Solver};
    \path (FlowSolver)+(0,-1.25) node (Droplet) [wa] {Droplet\\Advection Module};
    \path (Droplet)+(0,-1.25) node (ThermoModule) [wa] {Thermodynamic Module};
    \path (ThermoModule)+(0,-1.25) node (IcedAirfoil) [wa] {Iced Airfoil Geometry};
    \path (CleanAirfoil)+(8,0) node (FinalAirfoil) [wa] {Final Iced Airfoil Geometry};

    \path [draw, ->, thick] (CleanAirfoil.north) |- node [above] {} (FlowSolver.west);
    \path [draw, ->, thick] (FlowSolver.south) -- node [below] {} (Droplet.north);
    \path [draw, ->, thick] (Droplet.south) -- node [below] {} (ThermoModule.north);
    \path [draw, ->, thick] (ThermoModule.south) -- node [below] {} (IcedAirfoil.north);
    \path [draw, ->, thick] (IcedAirfoil.east) -| node [above] {} (FinalAirfoil.south);
    \path [draw, ->, thick] (IcedAirfoil.east) -- ++(0.75,0cm) |- node [above]
                      {} (FlowSolver.east);

    \begin{pgfonlayer}{background}
        \path (FlowSolver.west)+(-1,1) node (a) {};
        \path (IcedAirfoil.east)+(1,-1) node (b) {};
        \path[fill=orange!20,rounded corners, draw=black!50, dashed] (a) rectangle (b);
            
    \end{pgfonlayer}

\end{tikzpicture}

#+end_latex

** Airfoil Icing Code Details
- *Droplet advection*
  - Lagrangian formulation of equations of motion
  - Impingement details depend on ratio of inertial to viscous forces
     - Impacting droplets can bounce, deposit into surface film, or splash
  - Ratio of local to free-stream flux of droplets is calculated over airfoil
- *Thermodynamics*
  - Mass and energy balances of the liquid film on the airfoil surface
    used to determine ice accretion on airfoil
  - Mass enters film through impinging droplets, exits by freezing
  - Energy enters/exits through internal/kinetic energy of impinging
    droplets, energy transfer by ice accretion, convective
    heat transfer between ice/film/wall and the flow
  - Coupled mass/energy PDEs can be solved in one of two ways: (1)
    ``elephant gun": Jacobian-free Newton-Krylov (JFNK) iteration, or
    (2) guess solution, drive to steady-state
** State of Code: Advection Module

#+begin_latex
\begin{columns}[c]
  \column{0.5\textwidth}
    \centering
    \includegraphics[width=0.65\textwidth]{MVD52} \\
    {\bf MVD 52} \\
    \includegraphics[width=0.65\textwidth]{MVD154} \\
    {\bf MVD 154}
  \column{0.5\textwidth}
    \centering
    \includegraphics[width=0.65\textwidth]{MVD111} \\
    {\bf MVD 111} \\
    \includegraphics[width=0.65\textwidth]{MVD236} \\
    {\bf MVD 236}
\end{columns}
#+end_latex

- Advection module appears to be giving reasonable results for
  benchmark tests using different droplet distributions on a clean
  airfoil

** State of Code: Thermodynamic Module
- *Completed work*
  - Finite volume discretization of the mass/energy equations with
    appropriate upwinding (Roe scheme)
  - Modifications to Gigi's flow solver to compute/output convective
    heat transfer coefficient, skin friction
  - Basic MatLab prototyping for solving equations with (1) JFNK and (2)
    explicitly driving initial guess to steady-state
- *Remaining work*
  - Modify Spalart-Almaras turbulence model in flow solver for rough
    wall/icing application (will affect convective heat transfer)
  - Integrate MatLab prototype solver into main C++ icing code
  - Test, verify calculations!
  - Once working, do UQ studies on physical parameters (eg.,
    convective heat transfer distribution, droplet size and
    temperature distribution) affect aerodynamics



* UQ for DMD

** Motivation
- DMD models can change with (1) uncertain physical parameters, or (2) sensor noise
- Viewing this as a UQ problem has some potential advantages:
  - Some UQ tools can be computationally efficient relative to Monte Carlo sampling
  - Can investigate sensitivity of DMD models to different parameters
  - Can investigate sensitivity of DMD models to noise bias/scaling
  - Can assemble a surrogate model for how DMD models change over a parameter range
** Basic Demonstration: Parametric Uncertainty
- Stuart-Landau equation, $\mu = \mathcal{U}(1,1.2)$, $\beta = \mathcal{U}(0,0.2)$
\begin{equation*}
\begin{aligned}
\dot{r} &= \mu r - r^3 \\
\dot{\theta} &= \gamma - \beta r^2
\end{aligned}
\end{equation*}
- Observations are $\lbrace r^{-j} e^{i(k\theta)} \rbrace$, $j = -2,0$ and $k = -3...3$

#+begin_latex
\begin{columns}[c]
  \column{0.5\textwidth}
    \centering
    \includegraphics[width=0.99\textwidth]{SLeigs_PCE} \\
    {\bf PCE Evalss (129 Samples)}
  \column{0.5\textwidth}
    \centering
    \includegraphics[width=0.99\textwidth]{SLeigs_MC} \\
    {\bf Monte Carlo Evals (1000 Samples)}
\end{columns}
#+end_latex

** Basic Demonstration: Noise-Corrupted Data
#+begin_latex
\newcommand*{\horzbar}{\rule[.5ex]{2.5ex}{0.5pt}}
#+end_latex
\begin{equation*}
\dot{\bv{x}} =  \begin{bmatrix} 1 & -2 \\ 1 & -1 \end{bmatrix} \bv{x}
\end{equation*}

- Take data $X \in \mathbb{R}^{2\times100}$ as 100 discrete-time samples of system ($dt = 0.1$)
- Data is corrupted by noise matrix $N \in \mathbb{R}^{2\times100}$

\begin{equation*}
N = \begin{bmatrix} \horzbar & N_1(\mu_1,\sigma_1) & \horzbar \\ \horzbar & N_2(\mu_2,\sigma_2) & \horzbar \end{bmatrix}
\end{equation*}

#+begin_latex
\begin{columns}[c]
  \column{0.5\textwidth}
    \centering
    \includegraphics[width=0.75\textwidth]{NoisyEigsPCE} \\
    {\bf PCE Evals (337 Samples)}
  \column{0.5\textwidth}
    \centering
    \includegraphics[width=0.75\textwidth]{NoisyEigsMC} \\
    {\bf Monte Carlo Evals (1000 Samples)}
\end{columns}
#+end_latex

** Future Work
- Extending work to ``realistic" cases where the state dimension is large
