#+STARTUP: beamer
#+LaTeX_CLASS: beamer
#+LaTeX_CLASS_OPTIONS: [9pt]

#+latex_header: \mode<beamer>{\usetheme{Warsaw}}
#+latex_header: \mode<beamer>{\setbeamertemplate{blocks}[rounded][shadow=false]}
#+latex_header: \mode<beamer>{\addtobeamertemplate{block begin}{\pgfsetfillopacity{0.8}}{\pgfsetfillopacity{1}}}
#+latex_header: \mode<beamer>{\setbeamercolor{structure}{fg=orange}}
#+latex_header: \mode<beamer>{\setbeamercovered{transparent}}
#+latex_header: \AtBeginSection[]{\begin{frame}<beamer>\frametitle{Topic}\tableofcontents[currentsection]\end{frame}}

#+latex_header: \usepackage{subcaption}
#+latex_header: \usepackage{multimedia}
#+latex_header: \usepackage{tikz}
#+latex_header: \usepackage{subfigure,subfigmat}
#+latex_header: \usepackage{threeparttable}
#+latex_header: \usetikzlibrary{shapes,arrows,shadows}
#+latex_header: \usepackage{bm, amssymb, amsmath, array, pdfpages}

#+begin_latex
% Define my settings

\graphicspath{{Figures/}}
% Add Princeton shield logo
\addtobeamertemplate{frametitle}{}{%
\begin{tikzpicture}[remember picture,overlay]
\node[anchor=north east,yshift=2pt] at (current page.north east) {\includegraphics[height=0.7cm]{Shield}};
\end{tikzpicture}}
%
#+end_latex

#+latex_header: \newcommand{\bv}[1]{\mathbf{#1}}
#+latex_header: \newcommand{\diff}[2]{\frac{\partial #1}{\partial #2}}
#+latex_header: \newcommand{\beq}[0]{\begin{equation}}
#+latex_header: \newcommand{\eeq}[0]{\end{equation}}
#+latex_header: \newcommand{\beqa}[0]{\begin{eqnarray}}
#+latex_header: \newcommand{\eeqa}[0]{\end{eqnarray}}
#+latex_header: \newcommand{\beqq}[0]{\begin{equation*}}
#+latex_header: \newcommand{\eeqq}[0]{\end{equation*}}
#+latex_header: \newcommand{\bs}[1]{\boldsymbol{#1}}
#+latex_header: \newcommand{\ip}[2]{\langle #1, #2\rangle}
#+BEAMER_FRAME_LEVEL: 2

#+DATE: AIAA Aviation 2015 Conference \\ Dallas, TX \\ 26 June 2015
#+TITLE: Data-Driven Low-Dimensional Modeling and Uncertainty Quantification for Airfoil Icing
#+AUTHOR: Anthony DeGennaro \newline Clarence W. Rowley III \newline Luigi Martinelli \newline Princeton University
\institute{Princeton University}


* Motivation/Background

** Introduction
*Motivation*
- Wing icing is a serious issue for pilots
  - Massive flow separation, lower lift + higher drag
  - Unpredictable stall
- Wing ice shapes exhibit wide variation, sensitivity to physical
  parameters
  - Complex physics (coupled airflow-thermodynamics)
  - Uncertainty in physical parameters
*Research Goals*
- How can observed variations in ice shape be modeled
  efficiently with a low number of parameters?
- How does uncertainty in the ice shape create uncertainty in
  aerodynamic performance?

** Experimental/Computational Variation in Ice Shape

\vspace*{-0.5cm}\begin{figure}
  \begin{subfigmatrix}{2}
      \subfigure[Habashi, 2006]{\includegraphics[width=0.4\textwidth]{Habashi2006ShapeVariation}}
      \subfigure[Wright, 2004]{\includegraphics[width=0.4\textwidth]{Wright2004ShapeVariation}}
  \end{subfigmatrix}
\end{figure}

- Wide variation in experimental/computational ice shapes[fn:Habashi][fn:Wright]
- Suggests sensitivity to perturbations in underlying physical
  processes
- /UQ approach:/ parameterize the shape variation and study its
  effects on aerodynamics

[fn:Habashi] Beaugendre H., Morency M., and Habashi W.G. /Development
of a Second Generation in-Flight Icing Simulation Code/. Journal of
Fluids Engineering, ASME, 2006.
[fn:Wright] Wright W. and Potapczuk, M.G. /Semi-Empirical Modeling of
SLD Physics/, AIAA 2004-412. 42$^{nd}$ AIAA Aerospace Sciences
Meeting, Reno, NV, 2004.

** Relation to Previous Work

#+begin_latex
\begin{columns}[c]
  \column{0.33\textwidth}
    \centering
    \includegraphics[width=0.95\textwidth]{RidgeRVariation} \\
    \includegraphics[width=0.95\textwidth]{RidgeSVariation} \\
    {\bf Ridge}
  \column{0.33\textwidth}
    \centering
    \includegraphics[width=0.95\textwidth]{HornHVariation} \\
    \includegraphics[width=0.95\textwidth]{HornSVariation} \\
    {\bf Horn}
  \column{0.33\textwidth}
    \centering    
    \includegraphics[width=0.9\textwidth]{MC_surrogate_LargeUnc_CL} \\
    \includegraphics[width=0.9\textwidth]{MCgpcPDFLargeUnc_CL} \\
    {\bf Statistics}
\end{columns}
#+end_latex

- Previous study examined parameterized ridge and horn ice
  shapes[fn:DeGennaro]
- Approach was heuristic, not directly based on observed shape
  variations
- Parameter space was low dimensional; no low-dimensional modeling

[fn:DeGennaro] DeGennaro A., Rowley C.W., and Martinelli,
L. /Uncertainty Quantification for Airfoil Icing using Polynomial
Chaos Expansions/. To appear in Journal of Aircraft, 2015.


* Methodology

** Low-Dimensional Modeling

- The space of all ice shapes is infinite dimensional
- Consider small number of parameters that describe /likely/ shapes
- Analyze database of shapes from experiments/simulations
- *Proper Orthogonal Decomposition* [fn:POD]
  - Assume database of /M/ ice shapes
  - Each individual ice shape can be represented by a vector $\bv{x}
    \in \mathbb{R}^N$
  - Approximate $\bv{x}$ using some basis vectors $\psi_i$:
    \begin{equation*}
      \bv{x} \approx \sum_{i=1}^P a_i \psi_i
    \end{equation*}
  - Choose basis vectors to be the eigenvectors of the dataset
    covariance matrix
    \begin{equation*}
    \begin{aligned}
      \mathcal{R} \psi_k = \lambda_k \psi_k& \text{   where:   } \\ 
      \mathcal{R} = \frac{1}{M}\mathbf{X}\mathbf{X}^T \text{   and:   }&
      \mathbf{X} =
       \begin{bmatrix}
        \vline & & \vline \\
        x_1 & \cdots & x_M \\
        \vline & & \vline \\
       \end{bmatrix}
    \end{aligned}
    \end{equation*}
[fn:POD] Holmes P. et. al. /Turbulence, Coherent Structures, Dynamical
Systems and Symmetry/, Cambridge University Press, New York, 2012.

** Polynomial Chaos Expansions (PCE)

- *Polynomial Chaos Framework* [fn:XiuBook]
  - Let $\bv{Z} = (Z_1 \ldots Z_d)$ be $d$ random variables with PDF
    $\rho(\bv{Z})$ that parameterize ice
  - Let $\lbrace \Phi_k \rbrace$ denote the set of polynomials
    which are orthogonal w.r.t. $\rho(\bv{Z})$
  - Let $y(\bv{Z})$ denote the mapping from $\bv{Z}$ to an aerodynamic
    performance metric
- *Probabilistic Collocation Method:*
  - /Representation/ 
    \begin{equation*}
      y(\bv{Z}) \approx \sum_{|i|=0}^N y_i \Phi_i(\bv{Z})
    \end{equation*}
  - /Orthonormality/ 
    \begin{equation*}
    \begin{aligned}
      \ip{f}{g} &= \int_{\Gamma} f(\bv{z})g(\bv{z}) \rho(\bv{z}) d\bv{z} \\
      \ip{\Phi_i}{\Phi_j} &= \delta_{ij}
    \end{aligned}
    \end{equation*}
  - /Quadrature/ 
    \begin{equation*}
      y_k = \ip{y}{\Phi_k} \approx \sum_{i=0}^{Q}
    y(\bv{Z}^{(k)}) \Phi_k(\bv{Z}^{(k)}) w_k
    \end{equation*}
[fn:XiuBook] Xiu D. /Numerical Methods for Stochastic Computations: A
Spectral Method Approach/. Princeton University Press, 2010.

** PCE with Sparse Grids

#+begin_latex
\begin{columns}[c]
  \column{0.7\textwidth}
    \centering
    \includegraphics[width=0.95\textwidth]{SparseGrid1} \\
    \bf{Full Tensor Product vs. Sparse Grid}
  \column{0.3\textwidth}
    \centering
    \includegraphics[width=0.95\textwidth]{SparseGrid2} \\
    {\bf Anisotropic Grid}
\end{columns}
#+end_latex

- *Sparse Grids*[fn:LeMaitre]
  - /Efficient/: Only a subset of the full quadrature grid is used
    - For $d >> 1$, number of samples scales as $2^N {N+d \choose d} <<
      (N+1)^d$
  - /Adaptive/: Start with a coarse mesh, adaptively refine until
    achieve desired resolution
  - /Anisotropic/: Refine grid in most ``important" directions
  - Implemented in DAKOTA[fn:Dakota] (open-source UQ code)

[fn:LeMaitre] LeMaitre O. /Spectral Methods for Uncertainty
Quantification/. Springer, 2010.
[fn:Dakota] Adams et. al. /DAKOTA, A Multilevel Parallel
Object-Oriented Framework for Design Optimization.../ V. 5.3 User's
Manual. SAND2010-2183.


* Simulation Dataset

** Dataset Description 
\begin{figure}
  \centering
  \includegraphics[width=0.6\textwidth]{CRMHorn}
\end{figure}

- NASA Common Research Model (CRM), $65\%$ scale[fn:CRM]
  - 45 min accretion time, altitude = 10,000 ft, velocity = 232 knots,
    temperature = $-4^{\text{o}}$ C, MVD = 20 $\mu m$, LWC = 0.55
    $g/m^3$
[fn:CRM] Broeren A. et. al. /Swept-Wing Ice Accretion Characterization
and Aerodynamics/, AIAA 2013-2824.

** Low-Dimensional Modeling of Dataset
#+begin_latex
\begin{columns}[c]
  \column{0.3\textwidth}
    \centering
    \includegraphics[width=1.3\textwidth]{HornsUnaligned} \\
    \bf{Original Data}
  \column{0.3\textwidth}
    \centering
    \includegraphics[width=1.25\textwidth]{PODReconstruction2} \\
    {\bf POD Reconstruction}
  \column{0.3\textwidth}
    \centering
    \includegraphics[width=1.25\textwidth]{PODModes} \\
    {\bf POD Modes}
\end{columns}
#+end_latex
\vspace{1cm}
\begin{equation*}
N(s) = h \lbrace \bar{N}(as + b) + \sum_{i=1}^2 c_i \Phi_i(as + b)   \rbrace
\end{equation*}

- /h, a, b/ are scaling parameters
- $c_1, c_2$ are POD coefficients
- This collapses 100 different snapshots into 5 parameters

** 5-Dimensional UQ Study

#+begin_latex
\begin{columns}[c]
  \column{0.5\textwidth}
    \centering
    \includegraphics[width=.75\textwidth]{DifferentShapesPODModes} \\
    \bf{POD Modes} \\
    \includegraphics[width=.75\textwidth]{DifferentShapesWidth} \\
    \bf{Width}
  \column{0.5\textwidth}
    \centering
    \includegraphics[width=.75\textwidth]{DifferentShapesHeight} \\
    {\bf Height} \\
    \includegraphics[width=.75\textwidth]{DifferentShapesPosition} \\
    {\bf Position}    
\end{columns}
#+end_latex

- 2 POD coefficients (/shape/) + width, height, position parameters (/scaling/)

** Statistics

#+begin_latex
\begin{columns}[c]
  \column{0.37\textwidth}
    \centering
    \includegraphics[width=1\textwidth]{PDFCLMAX} \\
    $\bm{C_L}$ {\bf Statistics}
  \column{0.37\textwidth}
    \centering
    \includegraphics[width=1\textwidth]{PDFCDMAX} \\
    $\bm{C_D}$ {\bf Statistics}
\end{columns}

#+end_latex

|           | Width | Position | Height | POD 1 | POD 2 |
|-----------+-------+----------+--------+-------+------ |
| T ($C_L$) |  0.03 |  0.69    | 0.15   | 0.11  | 0.14  |

- Our surrogate is an explicit polynomial function of the input
  variables, making statistical inference easy/quick
- PCE surrogate computed using 1,103 sparse grid points
- Sobol index $T_i = \frac{\mathbb{E}\left[ Var\left(
  Y|Z_{-i}\right)\right]}{Var\left( Y\right)}$ is a measure of how much
  $Z_i$ contributes to the total variance of $Y(\bv{Z})$
- For our parameter ranges, position perturbation accounts for most of
  the statistical variation
** Statistical Inference

- Analyze statistical clustering of horns that produce bottom and top
  $10\%$ of $C_L$ variation

#+begin_latex
\begin{columns}[c]
  \column{0.40\textwidth}
    \centering
    \includegraphics[width=1\textwidth]{GoodHornParamLocs.png} \\
    {\bf Favorable Horns}
    \begin{itemize}
      \item Wider/rounded
      \item Lower surface
      \item Shorter
      \item Gentle downward skew
    \end{itemize}
  \column{0.40\textwidth}
    \centering
    \includegraphics[width=1\textwidth]{BadHornParamLocs.png} \\
    {\bf Unfavorable Horns}
    \begin{itemize}
      \item Sharper/narrower
      \item Upper surface
      \item Taller
      \item Sharp, upper skew shape
    \end{itemize}
\end{columns}

#+end_latex

** Flow Solutions

#+begin_latex
\begin{columns}[c]
  \column{0.30\textwidth}
    \centering
    \includegraphics[width=1\textwidth]{GoodHorn.png} \\
    {\bf Favorable Position}
    \includegraphics[width=1\textwidth]{GoodHornPOD.png} \\
    {\bf Favorable shape skew}
  \column{0.30\textwidth}
    \centering
    \includegraphics[width=1\textwidth]{BadHorn.png} \\
    {\bf Unfavorable Position}
    \includegraphics[width=1\textwidth]{BadHornPOD.png} \\
    {\bf Unfavorable shape skew}
\end{columns}

#+end_latex


* Experiment Dataset

** Dataset Description

\begin{figure}
  \centering
  \includegraphics[width=0.7\textwidth]{Dataset}
\end{figure}

- Business jet clean airfoil geometry[fn:Addy]
- 54 ice shapes, exposed to wide range of various icing conditions
  consistent with FAA certification guidelines
- POD dataset will consist of binary values defined on a static
  Cartesian mesh (`1' if mesh point is on the ice, `0' if not)

[fn:Addy] Addy, H.E. /Ice Accretions and Icing Effects for Modern
Airfoils/. NASA TR 2000-210031.

** Low-Dimensional Modeling of Dataset

#+begin_latex
\begin{columns}[c]
  \column{0.45\textwidth}
    \centering
    \hspace{-2.17em}
    \includegraphics[width=0.9\textwidth]{MEAN.png} \\
    {\bf Mean} \\
    \includegraphics[width=1\textwidth]{MODE2.png} \\
    {\bf Mode 2} \\
    \includegraphics[width=1\textwidth]{MODE4.png} \\
    {\bf Mode 4}
  \column{0.45\textwidth}
    \centering
    \includegraphics[width=1\textwidth]{MODE1.png} \\
    {\bf Mode 1} \\
    \includegraphics[width=1\textwidth]{MODE3.png} \\
    {\bf Mode 3} \\
    \includegraphics[width=1\textwidth]{MODE5.png} \\
    {\bf Mode 5}
\end{columns}

#+end_latex

- 8 Modes retained; this is where POD eigenvalue magnitudes have
  decayed by an order of magnitude
** Ice Shape Reconstructions

#+begin_latex
\begin{columns}[c]
  \column{0.45\textwidth}
    \centering
    \hspace{-0.5em}
    \includegraphics[width=1\textwidth]{UnfilteredReconstruction.png} \\
    {\bf Unfiltered Reconstruction} \\
    \includegraphics[width=1\textwidth]{ReconstructionE1} \\
    \includegraphics[width=1\textwidth]{ReconstructionE9} \\
  \column{0.45\textwidth}
    \centering
    \includegraphics[width=1\textwidth]{FilteredReconstruction.png} \\
    {\bf Filtered Reconstruction} \\
    \includegraphics[width=1\textwidth]{ReconstructionE3} \\
    \includegraphics[width=1\textwidth]{ReconstructionE4} \\
\end{columns}
\begin{center}
{\bf Ice Reconstructions}
\end{center}

#+end_latex
** Preliminary Findings

\begin{figure}
  \centering
  \includegraphics[width=0.7\textwidth]{GoodBadHornExamps}
\end{figure}

- *Green:* Horns which produce upper 10$\%$ of $C_L$
  - Lower amounts of ice accumulation
  - Ice mass concentrated on lower surface
- *Red:* Horns which produce lower 10$\%$ of $C_L$
  - Higher amounts of ice accumulation
  - Ice mass forms sharp upper surface horn
- Results derived from $\sim 5,500$ sparse grid evaluations
- More sparse grid evaluations are currently underway to produce a
  faithful, converged PCE surrogate



** Conclusions/Future Work

- *Conclusions*
  - Introduced a framework for studying the statistical effects of
    parameterized perturbations to airfoil ice shape
    - Approach is data-driven (not heuristic)
    - Low-dimensional modeling via Proper Orthogonal Decomposition (POD)
    - Uncertainty quantification via Polynomial Chaos Expansions (PCE)
  - Illustrated methodology on two example datasets

- *Future Work*
  - Finish UQ work on last dataset
  - First pre-process data into ``classes", and then apply framework
    separately to each class
  - Extend methodology to 3D datasets


* Computational-Based UQ

** Motivation
- *Investigate uncertainty in the physical process of icing*
  - Distribution of droplet diameters affects collection efficiency
  - Surface tension of SLDs varies with their temperature
  - Surface roughness could vary as SLDs impinge and freeze

#+begin_latex
\begin{columns}[c]
  \column{0.5\textwidth}
    \centering
    \includegraphics[width=1\textwidth]{FAADropletDist1} \\
    {\bf Freezing Drizzle MVD PDF}
    \includegraphics[width=0.4\textwidth]{SurfaceTensionVsTemp.jpeg} \\
    {\bf Surface Tension vs. Temperature}
  \column{0.5\textwidth}
    \centering
    \includegraphics[width=1\textwidth]{FAADropletDist2} \\
    {\bf Freezing Rain MVD PDF}
    \includegraphics[width=0.4\textwidth]{RoughnessGrowth.png} \\
    {\bf Roughness Growth}
\end{columns}
#+end_latex
** Droplet Diameter Distribution
#+begin_latex
\begin{columns}[c]
  \column{0.5\textwidth}
    \centering
    \includegraphics[width=1\textwidth]{FAADropletDist1} \\
    {\bf Freezing Drizzle MVD PDF}
  \column{0.5\textwidth}
    \centering
    \includegraphics[width=1\textwidth]{FAADropletDist2} \\
    {\bf Freezing Rain MVD PDF}
\end{columns}
#+end_latex

- Several MVD distributions exist for different flight conditions [fn:FAARegs]
- Each gives a different collection efficiency
- How much does collection efficiency and ice shape vary with MVD distribution?

[fn:FAARegs] Airplane and Engine Certification Requirements in
Supercooled Large Drop, Mixed Phase, and Ice Crystal Icing Conditions;
Final Rule. Federal Register, Vol. 79, No. 213.

** Surface Tension vs. Temperature
\begin{figure}
  \centering
  \includegraphics[width=0.33\textwidth]{SurfaceTensionVsTemp.jpeg} \\
  {\bf Surface Tension vs. Temperature}
\end{figure}

- Surface tension of SLDs varies with temperature [fn:SurfTens]
- Varying surface tension can affect collection efficiency
- Higher surface tension may give rise to ``beading" on surface
  (vs. deposition into film), which could affect surface roughness

[fn:SurfTens] Hruby, J. et. al. Surface Tension of Supercooled Water:
No Inflection Point down -25 Degrees
Celsius. J. Phys. Chem. Lett. 2014, 5, 425-28.

** Roughness Variations
\begin{figure}
  \centering
  \includegraphics[width=1\textwidth]{IcingRoughness.png} \\
  {\bf Roughness Growth}
\end{figure}

- *Surface roughness varies with parameters* [fn:Shin]
  - Roughness height increases with temperature and LWC
  - Beginning of roughness varies with temperature, speed, LWC
- *Surface roughness affects shape/aerodynamics* [fn:Shin]
  - Roughness elements probably protrude out of boundary layer and cause transition
  - Irregularity of shape should be calculated by ice accretion code, not treated as part of roughness model

[fn:Shin] Shin, J. Characteristics of Surface Roughness Associated
with Leading-Edge Ice Accretion. Journal of Aircraft, Vol. 33, No.2,
April 1996.

** Airfoil Icing Code Flowchart 

#+begin_latex
\fontsize{7}\selectfont
% Define the layers to draw the diagram
\pgfdeclarelayer{background}
\pgfdeclarelayer{foreground}
\pgfsetlayers{background,main,foreground}

% Define block styles used later

\tikzstyle{sensor}=[draw, fill=blue!20, text width=5em, 
    text centered, minimum height=2.5em,drop shadow]
\tikzstyle{ann} = [above, text width=5em, text centered]
\tikzstyle{wa} = [sensor, text width=7.5em, fill=blue!20, 
    minimum height=3em, rounded corners, drop shadow]

% Define distances for bordering
\def\blockdist{2.3}
\def\edgedist{2.5}

\begin{tikzpicture}
    \node (CleanAirfoil) [wa]  {Clean Airfoil Geometry};
    \path (CleanAirfoil)+(4,2.5) node (FlowSolver) [wa] {Mesh/Flow Solver};
    \path (FlowSolver)+(0,-1.25) node (DropletDist) [wa] {Droplet\\Statistics Module};
    \path (DropletDist)+(0,-1.25) node (SLDModule) [wa] {Droplet\\Dynamics Module};
    \path (SLDModule)+(0,-1.25) node (ThermoModule) [wa] {Thermodynamic Module};
    \path (ThermoModule)+(0,-1.25) node (IcedAirfoil) [wa] {Iced Airfoil Geometry};
    \path (CleanAirfoil)+(8,0) node (FinalAirfoil) [wa] {Final Iced Airfoil Geometry};

    \path [draw, ->, thick] (CleanAirfoil.north) |- node [above] {} (FlowSolver.west);
    \path [draw, ->, thick] (FlowSolver.south) -- node [below] {} (DropletDist.north);
    \path [draw, ->, thick] (DropletDist.south) -- node [below] {} (SLDModule.north);
    \path [draw, ->, thick] (SLDModule.south) -- node [below] {} (ThermoModule.north);
    \path [draw, ->, thick] (ThermoModule.south) -- node [below] {} (IcedAirfoil.north);
    \path [draw, ->, thick] (IcedAirfoil.east) -| node [above] {} (FinalAirfoil.south);
    \path [draw, ->, thick] (IcedAirfoil.east) -- ++(0.75,0cm) |- node [above]
                      {} (FlowSolver.east);

    \begin{pgfonlayer}{background}
        \path (FlowSolver.west)+(-1,1) node (a) {};
        \path (IcedAirfoil.east)+(1,-1) node (b) {};
        \path[fill=orange!20,rounded corners, draw=black!50, dashed] (a) rectangle (b);
            
    \end{pgfonlayer}
    \begin{pgfonlayer}{background}
        \path (DropletDist.west)+(-0.5,0.6) node (a) {};
        \path (SLDModule.east)+(0.5,-0.6) node (b) {};
        \path[fill=orange!40,rounded corners, draw=black!50, dashed] (a) rectangle (b);
            
    \end{pgfonlayer}

\end{tikzpicture}

#+end_latex

** Preliminary Intermediate Results: Mass Flux

#+begin_latex
\begin{columns}[c]
  \column{0.5\textwidth}
    \centering
    \includegraphics[width=1\textwidth]{BetaSample} \\
    {\bf Statistics}
  \column{0.5\textwidth}
    \centering
    \includegraphics[width=1\textwidth]{BetaComparison} \\
    {\bf Validation}
\end{columns}
#+end_latex

- Collection efficiency is the ratio of surface to free-stream water flux
- Results with/without splashing module are shown
- Agreement is marginal; may require additional work/analysis of the
  splashing module

** Conclusions/Future Work

*Conclusions*
- Airfoil icing is a process subject to much uncertainty
  - Wide variation in ice shapes
  - Sensitivity to perturbations in physical conditions
- We have briefly demonstrated three approaches to quantifying
  uncertainty in this problem
  - Heuristic parameterization
  - Data-based parameterization
  - Stochastic processes and in computational models 
*Future Work*
- Parameterized UQ
  - Investigate effect of more shape parameters
  - Extend efforts to 3D wing icing
- Computational modeling
  - Continue development and testing of icing code
  - Use icing code to investigate statistical variation of ice shape
